# Generated by Django 4.2.11 on 2024-04-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deptEnews', '0002_remove_article_topic_newsletter_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='articles',
        ),
    ]
