# Generated by Django 4.2.11 on 2024-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptEnews', '0003_remove_article_newsletter_remove_newsletter_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
