# Generated by Django 4.2.11 on 2024-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptEnews', '0004_alter_newsletter_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
