# Generated by Django 4.2.11 on 2024-04-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deptEnews', '0005_alter_newsletter_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deptEnews.newsletter'),
        ),
    ]
