# Generated by Django 4.2.11 on 2024-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptEnews', '0006_article_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='event',
            field=models.ManyToManyField(to='deptEnews.event'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='announcement',
            field=models.ManyToManyField(to='deptEnews.announcement'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='employee',
            field=models.ManyToManyField(to='deptEnews.employee'),
        ),
    ]
